version: '3'

services:
  database:
    container_name: database
    image: mysql:5.7 #https://laravel.com/docs/7.x/database
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: Passw0rd
      MYSQL_ROOT_PASSWORD: Passw0rd
    volumes:
      - laravel-photo-sharing-app-database-data:/var/lib/mysql:cached

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/srv:cached
    working_dir: /srv
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src/public:/srv/public:cached
      # 画像表示には下記のマウントが必要
      #  - 画像URL
      #    - http://localhost:8000/storage/xxx/xxx/hoge.jpeg
      #  - 上記の画像URLを表示する為には、Nginx コンテナに /storage/xxx/xxx/hoge.jpeg が必要
      #  - `php artisan storage:link` で php-fpm コンテナ内に symbolic link (public/storage -> /srv/storage/app/public) を貼るだけでは 404 になる
      - ./src/storage/app/public:/srv/public/storage:cached
    depends_on:
      - php-fpm

volumes:
  laravel-photo-sharing-app-database-data:
    external:
      name: laravel-photo-sharing-app-database-data
